package restaurante.Vistas;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public final class Principal extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    
    /**
     * Creates new form principal
     */
    public Principal() {

        initComponents();

        getContentPane().add(background);

        rellenarHora();
        rellenarFecha();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        jLFecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLGestión = new javax.swing.JLabel();
        empleadoBtn = new javax.swing.JPanel();
        jLEmpleados = new javax.swing.JLabel();
        mesasBtn = new javax.swing.JPanel();
        jLMesas = new javax.swing.JLabel();
        productosBtn = new javax.swing.JPanel();
        jLProductos = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLServicio = new javax.swing.JLabel();
        pedidosBtn = new javax.swing.JPanel();
        jLPedidos = new javax.swing.JLabel();
        reservasBtn = new javax.swing.JPanel();
        jLReservas = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLAdministración = new javax.swing.JLabel();
        consultasBtn = new javax.swing.JPanel();
        jLConsultas = new javax.swing.JLabel();
        jLHora = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        menuBtn = new javax.swing.JPanel();
        menuTxt = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        maxBtn = new javax.swing.JPanel();
        maxTxt = new javax.swing.JLabel();
        minBtn = new javax.swing.JPanel();
        minTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 25, 25));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 900));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        background.setBackground(new java.awt.Color(255, 150, 0));
        background.setForeground(new java.awt.Color(255, 150, 0));
        background.setName(""); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(1024, 720));

        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/img/CapybaraRestó.png"))); // NOI18N
        bg.setAlignmentX(0.5F);
        bg.setFocusable(false);
        bg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bg.setPreferredSize(new java.awt.Dimension(1200, 720));

        menu.setBackground(new java.awt.Color(25, 25, 25));
        menu.setForeground(new java.awt.Color(255, 150, 0));
        menu.setMaximumSize(new java.awt.Dimension(160, 32767));
        menu.setPreferredSize(new java.awt.Dimension(160, 0));

        jLFecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLFecha.setForeground(new java.awt.Color(204, 204, 204));
        jLFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFecha.setText("{dia} | {mes} | {año}");
        jLFecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLFecha.setMaximumSize(new java.awt.Dimension(160, 20));
        jLFecha.setMinimumSize(new java.awt.Dimension(160, 20));
        jLFecha.setPreferredSize(new java.awt.Dimension(160, 20));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        jLGestión.setBackground(new java.awt.Color(25, 25, 25));
        jLGestión.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLGestión.setForeground(new java.awt.Color(204, 204, 204));
        jLGestión.setText("Gestión");

        empleadoBtn.setBackground(new java.awt.Color(25, 25, 25));

        jLEmpleados.setBackground(new java.awt.Color(25, 25, 25));
        jLEmpleados.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLEmpleados.setForeground(new java.awt.Color(204, 204, 204));
        jLEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEmpleados.setText("Empleados");
        jLEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLEmpleadosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLEmpleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLEmpleadosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout empleadoBtnLayout = new javax.swing.GroupLayout(empleadoBtn);
        empleadoBtn.setLayout(empleadoBtnLayout);
        empleadoBtnLayout.setHorizontalGroup(
            empleadoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        empleadoBtnLayout.setVerticalGroup(
            empleadoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLEmpleados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        mesasBtn.setBackground(new java.awt.Color(25, 25, 25));

        jLMesas.setBackground(new java.awt.Color(25, 25, 25));
        jLMesas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLMesas.setForeground(new java.awt.Color(204, 204, 204));
        jLMesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMesas.setText("Mesas");
        jLMesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMesasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLMesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLMesasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mesasBtnLayout = new javax.swing.GroupLayout(mesasBtn);
        mesasBtn.setLayout(mesasBtnLayout);
        mesasBtnLayout.setHorizontalGroup(
            mesasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mesasBtnLayout.setVerticalGroup(
            mesasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLMesas, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        productosBtn.setBackground(new java.awt.Color(25, 25, 25));

        jLProductos.setBackground(new java.awt.Color(25, 25, 25));
        jLProductos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLProductos.setForeground(new java.awt.Color(204, 204, 204));
        jLProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLProductos.setText("Productos");
        jLProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLProductosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout productosBtnLayout = new javax.swing.GroupLayout(productosBtn);
        productosBtn.setLayout(productosBtnLayout);
        productosBtnLayout.setHorizontalGroup(
            productosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        productosBtnLayout.setVerticalGroup(
            productosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));

        jLServicio.setBackground(new java.awt.Color(25, 25, 25));
        jLServicio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLServicio.setForeground(new java.awt.Color(204, 204, 204));
        jLServicio.setText("Servicio");
        jLServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pedidosBtn.setBackground(new java.awt.Color(25, 25, 25));

        jLPedidos.setBackground(new java.awt.Color(25, 25, 25));
        jLPedidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLPedidos.setForeground(new java.awt.Color(204, 204, 204));
        jLPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPedidos.setText("Gestor de Pedidos");
        jLPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLPedidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLPedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLPedidosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pedidosBtnLayout = new javax.swing.GroupLayout(pedidosBtn);
        pedidosBtn.setLayout(pedidosBtnLayout);
        pedidosBtnLayout.setHorizontalGroup(
            pedidosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pedidosBtnLayout.setVerticalGroup(
            pedidosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        reservasBtn.setBackground(new java.awt.Color(25, 25, 25));

        jLReservas.setBackground(new java.awt.Color(25, 25, 25));
        jLReservas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLReservas.setForeground(new java.awt.Color(204, 204, 204));
        jLReservas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLReservas.setText("Gestor de Reservas");
        jLReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLReservasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLReservasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLReservasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout reservasBtnLayout = new javax.swing.GroupLayout(reservasBtn);
        reservasBtn.setLayout(reservasBtnLayout);
        reservasBtnLayout.setHorizontalGroup(
            reservasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        reservasBtnLayout.setVerticalGroup(
            reservasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));

        jLAdministración.setBackground(new java.awt.Color(25, 25, 25));
        jLAdministración.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLAdministración.setForeground(new java.awt.Color(204, 204, 204));
        jLAdministración.setText("Administración");
        jLAdministración.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        consultasBtn.setBackground(new java.awt.Color(25, 25, 25));

        jLConsultas.setBackground(new java.awt.Color(25, 25, 25));
        jLConsultas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLConsultas.setForeground(new java.awt.Color(204, 204, 204));
        jLConsultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLConsultas.setText("Informes de Ingresos");
        jLConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLConsultasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLConsultasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLConsultasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout consultasBtnLayout = new javax.swing.GroupLayout(consultasBtn);
        consultasBtn.setLayout(consultasBtnLayout);
        consultasBtnLayout.setHorizontalGroup(
            consultasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        consultasBtnLayout.setVerticalGroup(
            consultasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jLHora.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLHora.setForeground(new java.awt.Color(204, 204, 204));
        jLHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLHora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLHora.setMaximumSize(new java.awt.Dimension(160, 20));
        jLHora.setMinimumSize(new java.awt.Dimension(160, 20));
        jLHora.setPreferredSize(new java.awt.Dimension(160, 20));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLServicio))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLGestión))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLAdministración))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empleadoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mesasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reservasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(consultasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pedidosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(167, 167, 167))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLHora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLGestión)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empleadoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mesasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(productosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pedidosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(reservasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAdministración)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(25, 25, 25));
        header.setForeground(new java.awt.Color(255, 150, 0));
        header.setMaximumSize(new java.awt.Dimension(32767, 30));
        header.setPreferredSize(new java.awt.Dimension(1030, 30));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        menuBtn.setBackground(new java.awt.Color(25, 25, 25));
        menuBtn.setPreferredSize(new java.awt.Dimension(20, 20));

        menuTxt.setBackground(new java.awt.Color(0, 0, 0));
        menuTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/img/Carpixs.png"))); // NOI18N
        menuTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuBtnLayout = new javax.swing.GroupLayout(menuBtn);
        menuBtn.setLayout(menuBtnLayout);
        menuBtnLayout.setHorizontalGroup(
            menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuBtnLayout.setVerticalGroup(
            menuBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBtnLayout.createSequentialGroup()
                .addComponent(menuTxt)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        exitBtn.setBackground(new java.awt.Color(25, 25, 25));
        exitBtn.setMinimumSize(new java.awt.Dimension(20, 20));
        exitBtn.setPreferredSize(new java.awt.Dimension(20, 20));

        exitTxt.setBackground(new java.awt.Color(255, 150, 0));
        exitTxt.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitTxt.setPreferredSize(new java.awt.Dimension(20, 20));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        maxBtn.setBackground(new java.awt.Color(25, 25, 25));
        maxBtn.setForeground(new java.awt.Color(204, 204, 204));
        maxBtn.setMinimumSize(new java.awt.Dimension(20, 20));
        maxBtn.setPreferredSize(new java.awt.Dimension(20, 20));

        maxTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/img/icons8-maximizar-la-ventana-20.png"))); // NOI18N
        maxTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout maxBtnLayout = new javax.swing.GroupLayout(maxBtn);
        maxBtn.setLayout(maxBtnLayout);
        maxBtnLayout.setHorizontalGroup(
            maxBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(maxBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(maxBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(maxTxt)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        maxBtnLayout.setVerticalGroup(
            maxBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(maxBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(maxBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(maxTxt)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        minBtn.setBackground(new java.awt.Color(25, 25, 25));
        minBtn.setForeground(new java.awt.Color(204, 204, 204));
        minBtn.setMinimumSize(new java.awt.Dimension(20, 20));
        minBtn.setPreferredSize(new java.awt.Dimension(20, 20));

        minTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/img/icons8-minimizar-la-ventana-20.png"))); // NOI18N
        minTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minBtnLayout = new javax.swing.GroupLayout(minBtn);
        minBtn.setLayout(minBtnLayout);
        minBtnLayout.setHorizontalGroup(
            minBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        minBtnLayout.setVerticalGroup(
            minBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minBtnLayout.createSequentialGroup()
                .addComponent(minTxt)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(maxBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                        .addGap(118, 118, 118))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(59, 59, 59))))
        );

        getContentPane().add(background);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea cerrar la aplicación?", null, JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitTxtMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.RED);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(new Color(25, 25, 25));
    }//GEN-LAST:event_exitTxtMouseExited

    private void menuTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTxtMouseEntered
        menuBtn.setBackground(new Color(255, 150, 0));
    }//GEN-LAST:event_menuTxtMouseEntered

    private void menuTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTxtMouseExited
        menuBtn.setBackground(new Color(25, 25, 25));
    }//GEN-LAST:event_menuTxtMouseExited

    private void jLEmpleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLEmpleadosMouseEntered
        empleadoBtn.setBackground(new Color(60, 63, 65));
    }//GEN-LAST:event_jLEmpleadosMouseEntered

    private void jLEmpleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLEmpleadosMouseExited
        empleadoBtn.setBackground(new Color(25, 25, 25));
    }//GEN-LAST:event_jLEmpleadosMouseExited

    private void jLEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLEmpleadosMouseClicked
        GestorEmpleados gestorEmpleados = new GestorEmpleados(this);

        int x = (this.getWidth() - gestorEmpleados.getWidth()) / 2;
        int y = (this.getHeight() - gestorEmpleados.getHeight()) / 2;

        background.add(gestorEmpleados, 0);
        background.revalidate();
        background.repaint();

        gestorEmpleados.setVisible(true);
        gestorEmpleados.setLocation(x, y);
    }//GEN-LAST:event_jLEmpleadosMouseClicked

    private void jLMesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMesasMouseEntered
        mesasBtn.setBackground(new Color(60, 63, 65));
    }//GEN-LAST:event_jLMesasMouseEntered

    private void jLMesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMesasMouseExited
        mesasBtn.setBackground(new Color(25, 25, 25));
    }//GEN-LAST:event_jLMesasMouseExited

    private void jLMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMesasMouseClicked
        GestorMesa gestorMesa = new GestorMesa(this);

        int x = (this.getWidth() - gestorMesa.getWidth()) / 2;
        int y = (this.getHeight() - gestorMesa.getHeight()) / 2;

        background.add(gestorMesa, 0);
        background.revalidate();
        background.repaint();

        gestorMesa.setVisible(true);
        gestorMesa.setLocation(x, y);
    }//GEN-LAST:event_jLMesasMouseClicked

    private void jLProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProductosMouseEntered
        productosBtn.setBackground(new Color(60, 63, 65));
    }//GEN-LAST:event_jLProductosMouseEntered

    private void jLProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProductosMouseExited
        productosBtn.setBackground(new Color(25, 25, 25));
    }//GEN-LAST:event_jLProductosMouseExited

    private void jLProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLProductosMouseClicked
        GestorProductos gestorProductos = new GestorProductos(this);

        int x = (this.getWidth() - gestorProductos.getWidth()) / 2;
        int y = (this.getHeight() - gestorProductos.getHeight()) / 2;

        background.add(gestorProductos, 0);
        background.revalidate();
        background.repaint();

        gestorProductos.setVisible(true);
        gestorProductos.setLocation(x, y);
    }//GEN-LAST:event_jLProductosMouseClicked

    private void jLPedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLPedidosMouseEntered
        pedidosBtn.setBackground(new Color(60, 63, 65));
    }//GEN-LAST:event_jLPedidosMouseEntered

    private void jLPedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLPedidosMouseExited
        pedidosBtn.setBackground(new Color(25, 25, 25));
    }//GEN-LAST:event_jLPedidosMouseExited

    private void jLPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLPedidosMouseClicked
        GestorPedidos gestorPedidos = new GestorPedidos(this);

        int x = (this.getWidth() - gestorPedidos.getWidth()) / 2;
        int y = (this.getHeight() - gestorPedidos.getHeight()) / 2;

        background.add(gestorPedidos, 0);
        background.revalidate();
        background.repaint();

        gestorPedidos.setVisible(true);
        gestorPedidos.setLocation(x, y);
    }//GEN-LAST:event_jLPedidosMouseClicked

    private void jLReservasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLReservasMouseEntered
        reservasBtn.setBackground(new Color(60, 63, 65));
    }//GEN-LAST:event_jLReservasMouseEntered

    private void jLReservasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLReservasMouseExited
        reservasBtn.setBackground(new Color(25, 25, 25));
    }//GEN-LAST:event_jLReservasMouseExited

    private void jLReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLReservasMouseClicked
        GestorReservas gestorReservas = new GestorReservas(this);

        int x = (this.getWidth() - gestorReservas.getWidth()) / 2;
        int y = (this.getHeight() - gestorReservas.getHeight()) / 2;

        background.add(gestorReservas, 0);
        background.revalidate();
        background.repaint();

        gestorReservas.setVisible(true);
        gestorReservas.setLocation(x, y);
    }//GEN-LAST:event_jLReservasMouseClicked

    private void jLConsultasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLConsultasMouseEntered
        consultasBtn.setBackground(new Color(60, 63, 65));
    }//GEN-LAST:event_jLConsultasMouseEntered

    private void jLConsultasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLConsultasMouseExited
        consultasBtn.setBackground(new Color(25, 25, 25));
    }//GEN-LAST:event_jLConsultasMouseExited

    private void jLConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLConsultasMouseClicked
        GestorInforme gestorInformes = new GestorInforme(this);

        int x = (this.getWidth() - gestorInformes.getWidth()) / 2;
        int y = (this.getHeight() - gestorInformes.getHeight()) / 2;

        background.add(gestorInformes, 0);
        background.revalidate();
        background.repaint();

        gestorInformes.setVisible(true);
        gestorInformes.setLocation(x, y);
        
    }//GEN-LAST:event_jLConsultasMouseClicked

    private void minTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minTxtMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            setState(Principal.ICONIFIED);
        }
    }//GEN-LAST:event_minTxtMouseClicked

    private void maxTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxTxtMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (getExtendedState() == Principal.MAXIMIZED_BOTH) {
                // Restaurar la ventana si ya está maximizada
                setExtendedState(Principal.NORMAL);
            } else {
                // Maximizar la ventana si no está maximizada
                setExtendedState(Principal.MAXIMIZED_BOTH);
            }
        }
    }//GEN-LAST:event_maxTxtMouseClicked

    private void maxTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxTxtMouseEntered
        maxBtn.setBackground(new Color(60, 63, 65));
    }//GEN-LAST:event_maxTxtMouseEntered

    private void maxTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxTxtMouseExited
        maxBtn.setBackground(new Color(25, 25, 25));
    }//GEN-LAST:event_maxTxtMouseExited

    private void minTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minTxtMouseEntered
        minBtn.setBackground(new Color(60, 63, 65));
    }//GEN-LAST:event_minTxtMouseEntered

    private void minTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minTxtMouseExited
        minBtn.setBackground(new Color(25, 25, 25));
    }//GEN-LAST:event_minTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel bg;
    private javax.swing.JPanel consultasBtn;
    private javax.swing.JPanel empleadoBtn;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLAdministración;
    private javax.swing.JLabel jLConsultas;
    private javax.swing.JLabel jLEmpleados;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLGestión;
    private javax.swing.JLabel jLHora;
    private javax.swing.JLabel jLMesas;
    private javax.swing.JLabel jLPedidos;
    private javax.swing.JLabel jLProductos;
    private javax.swing.JLabel jLReservas;
    private javax.swing.JLabel jLServicio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel maxBtn;
    private javax.swing.JLabel maxTxt;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuBtn;
    private javax.swing.JLabel menuTxt;
    private javax.swing.JPanel mesasBtn;
    private javax.swing.JPanel minBtn;
    private javax.swing.JLabel minTxt;
    private javax.swing.JPanel pedidosBtn;
    private javax.swing.JPanel productosBtn;
    private javax.swing.JPanel reservasBtn;
    // End of variables declaration//GEN-END:variables

    public void rellenarFecha() {
        LocalDate date = LocalDate.now();
        int year = date.getYear();
        int month = date.getMonthValue();
        int day = date.getDayOfMonth();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        jLFecha.setText(day + " | " + meses[month - 1] + " | " + year);
    }

    public void rellenarHora() {
        int delay = 1000; //1000 Milisegundos = 1 Segundo

        Timer timer = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formato = new SimpleDateFormat("HH:mm");
                String hora = formato.format(now);
                jLHora.setText(hora);
            }
        });
        timer.start();
    }

}
